In [1]:
import numpy as np

In [4]:
np.version.version

'1.23.4'

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
x = np.array([100, 20, 34])

In [11]:
print("Size of the array: ",
      x.size)

Size of the array:  3


In [12]:
print("Memory size of one array element in bytes: ",
      x.itemsize)

Memory size of one array element in bytes:  8


In [13]:
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

Memory size of numpy array in bytes: 24


In [14]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [15]:
np.arange(10) == 4

array([False, False, False, False,  True, False, False, False, False,
       False])

In [19]:
b=np.array([int(x==4) for x in range(10)])

In [20]:
print(b)

[0 0 0 0 1 0 0 0 0 0]


In [22]:
np.arange(40)+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
x=np.arange(1,20)

In [24]:
print (x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
x=x[::-1]

In [26]:
print(x)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [27]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
array = np.array([4,6,0,0,0,4,89])

In [29]:
print(array)

[ 4  6  0  0  0  4 89]


In [30]:
print(np.any(array))

True


In [31]:
array_2D=np.identity(3)

In [32]:
print('3x3 matrix:')

3x3 matrix:


In [33]:
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
x = np.random.random((10,10))

In [37]:
print(x)

[[0.31923041 0.89815875 0.64054822 0.1896131  0.95752158 0.02071928
  0.45315306 0.75976505 0.49215722 0.02150386]
 [0.77108247 0.71566832 0.96937482 0.01888173 0.71659806 0.2412457
  0.49150996 0.69763268 0.99135889 0.82932155]
 [0.03746039 0.20510398 0.76718637 0.74107584 0.27670159 0.65751826
  0.80322791 0.13625292 0.49968501 0.43115407]
 [0.64981348 0.09949058 0.77291545 0.15685398 0.21163225 0.74965495
  0.68208886 0.70816015 0.95233015 0.07995262]
 [0.42168299 0.3599512  0.31361301 0.74358378 0.5467292  0.76195242
  0.4323817  0.64871486 0.47729777 0.97522514]
 [0.91740884 0.10951056 0.42058475 0.22834871 0.03211297 0.6236409
  0.05893992 0.34785041 0.29613538 0.01656341]
 [0.93248194 0.52250784 0.92795626 0.38854605 0.64698738 0.08525732
  0.92688308 0.86791538 0.25934988 0.53503587]
 [0.39369812 0.45765468 0.80273051 0.10860689 0.98770741 0.02056722
  0.34228473 0.71776071 0.46082035 0.19722671]
 [0.35603007 0.42147084 0.48663112 0.16340537 0.2235248  0.12855594
  0.57430172 0

In [38]:
xmin, xmax = x.min() , x.max()

In [39]:
print(xmin, xmax)

0.016563407788483087 0.9913588899856584


In [40]:
Z = np.random.random(30) 

In [41]:
m = Z.mean() 

In [42]:
print(m)

0.6146138165070468


In [43]:
Z = np.ones((10,10)) 

In [44]:
Z[1:-1,1:-1] = 0 

In [45]:
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [46]:
Z = np.ones((5,5)) 

In [47]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0) 

In [48]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [49]:
print(0 * np.nan) 

nan


In [50]:
print(np.nan == np.nan) 

False


In [51]:
print(np.inf > np.nan) 

False


In [52]:
print(np.nan - np.nan) 

nan


In [53]:
print(0.3 == 3 * 0.1)

False


In [54]:
Z = np.diag(1+np.arange(4),k=-1) 

In [55]:
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [56]:
Z = np.zeros((8,8),dtype=int) 

In [57]:
Z[1::2,::2] = 1 

In [58]:
Z[::2,1::2] = 1 

In [59]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [60]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [61]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4)) 

In [62]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [63]:
Z = np.random.random((5,5))

In [64]:
Zmax,Zmin = Z.max(), Z.min()

In [65]:
Z = (Z - Zmin)/(Zmax - Zmin)

In [67]:
print(Z)

[[0.2380285  0.52064232 0.94649022 0.42643442 0.68665824]
 [0.94390414 0.19191283 0.83711046 0.16120703 0.6915483 ]
 [0.03554399 0.         0.26146056 1.         0.59585415]
 [0.84771249 0.63223288 0.67285847 0.24268365 0.14394323]
 [0.708755   0.45354658 0.86587697 0.19364473 0.33343237]]


In [68]:
return to do 23

SyntaxError: invalid syntax (849615428.py, line 1)

In [69]:
x = np.random.random((5,3))

In [70]:
print(x)

[[0.21032928 0.33184101 0.3965066 ]
 [0.59482231 0.82516331 0.84244399]
 [0.82232701 0.80200637 0.72146121]
 [0.58790782 0.42788662 0.38781987]
 [0.93270022 0.71245374 0.96304341]]


In [71]:
y = np.random.random((3,2))

In [72]:
print(y)

[[0.94104123 0.01986222]
 [0.2504066  0.40266979]
 [0.29787895 0.62433531]]


In [73]:
z = np.dot(x, y)

In [74]:
print(z)


[[0.39913467 0.38535302]
 [1.01732499 0.87005035]
 [1.18957942 0.78971068]
 [0.77591451 0.42610381]
 [1.34298284 0.90667109]]


In [75]:
Z = np.arange(11)

In [76]:
Z[(3 < Z) & (Z <= 8)] *= -1

In [77]:
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [78]:
print(sum(range(5),-1))

9


In [79]:
from numpy import *

In [80]:
print(sum(range(5),-1))

10


In [81]:
Z**Z

ValueError: Integers to negative integer powers are not allowed.

In [82]:
Z <- Z

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [83]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j, -0. -8.j,  0. +9.j,  0.+10.j])

In [84]:
np.array(0) / np.array(0)

/var/folders/kp/rvknddyx7xd6z400rct2634h0000gn/T/ipykernel_41555/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [85]:
np.array(0) // np.array(0)

/var/folders/kp/rvknddyx7xd6z400rct2634h0000gn/T/ipykernel_41555/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [89]:
array = np.array([1.,2.,3.,4.,5.])

In [91]:
res = np.round(array)

In [92]:
print(res)

[1. 2. 3. 4. 5.]


not sure about this one above

In [93]:
a = np.array([2, 4, 7, 1, 4])

In [94]:
b = np.array([7, 2, 9, 0, 5])

In [95]:
print("Original arrays", a, ' ', b)

Original arrays [2 4 7 1 4]   [7 2 9 0 5]


In [96]:
c = np.intersect1d(a, b)

In [97]:
print("Common values", c)

Common values [2 7]


In [100]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [101]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [102]:
today = np.datetime64('today', 'D')

In [103]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

In [104]:
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [105]:
print(today)

2022-11-20


In [106]:
print(yesterday)

2022-11-19


In [107]:
print(tomorrow)

2022-11-21


In [109]:
Z = np.arange('2016-08', '2016-09', dtype='datetime64[D]')

In [110]:
print(Z)

['2016-08-01' '2016-08-02' '2016-08-03' '2016-08-04' '2016-08-05'
 '2016-08-06' '2016-08-07' '2016-08-08' '2016-08-09' '2016-08-10'
 '2016-08-11' '2016-08-12' '2016-08-13' '2016-08-14' '2016-08-15'
 '2016-08-16' '2016-08-17' '2016-08-18' '2016-08-19' '2016-08-20'
 '2016-08-21' '2016-08-22' '2016-08-23' '2016-08-24' '2016-08-25'
 '2016-08-26' '2016-08-27' '2016-08-28' '2016-08-29' '2016-08-30'
 '2016-08-31']


In [111]:
a = np.arange(9).reshape(3,3)

In [112]:
b = np.transpose(a)

In [114]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
b

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [116]:
b[0,1] = 100

In [117]:
b

array([[  0, 100,   6],
       [  1,   4,   7],
       [  2,   5,   8]])

In [118]:
a

array([[  0,   1,   2],
       [100,   4,   5],
       [  6,   7,   8]])

missing item 36

In [125]:
x = np.zeros((5,5))

In [126]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [127]:
x += np.arange(5)

In [128]:
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [129]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]

In [130]:
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [131]:
x = np.random.random(10)

In [132]:
x

array([0.30349135, 0.05412096, 0.5863962 , 0.39717233, 0.1146399 ,
       0.4534077 , 0.77192601, 0.47562833, 0.58764257, 0.26964004])

In [134]:
x.sort()

In [135]:
x

array([0.05412096, 0.1146399 , 0.26964004, 0.30349135, 0.39717233,
       0.4534077 , 0.47562833, 0.5863962 , 0.58764257, 0.77192601])