In [47]:
import pandas as pd
import numpy as np

In [48]:
table=np.random.randint(1,100, size=(5,10))

In [49]:
table

array([[ 8,  7, 38, 48,  4, 30, 27, 31, 45, 51],
       [46, 58, 78, 51, 10,  1, 55, 85, 79, 73],
       [84, 78, 77, 70, 96, 86, 10, 88, 70, 95],
       [46, 65, 33, 60,  9, 99, 99, 47, 68, 27],
       [35, 14, 55, 34, 10, 75, 58, 11, 76, 32]])

In [51]:
row3=table[2]

In [52]:
row3

array([84, 78, 77, 70, 96, 86, 10, 88, 70, 95])

In [53]:
col3=table[:,2]

In [54]:
col3

array([38, 78, 77, 33, 55])

In [55]:
org = pd.DataFrame(table,
                columns=['A','B','C','D','E','F','G','H', 'I', 'J'],
                index = ['first', 'second', 'third', 'fourth', 'fifth'])

In [56]:
org

A   B   C   D   E   F   G   H   I   J
first    8   7  38  48   4  30  27  31  45  51
second  46  58  78  51  10   1  55  85  79  73
third   84  78  77  70  96  86  10  88  70  95
fourth  46  65  33  60   9  99  99  47  68  27
fifth   35  14  55  34  10  75  58  11  76  32

In [57]:
org.loc['fifth']

A    35
B    14
C    55
D    34
E    10
F    75
G    58
H    11
I    76
J    32
Name: fifth, dtype: int64

In [58]:
org.loc['fifth'] = [7,7,7,7,7,7,7,7,7,7]

In [59]:
org

A   B   C   D   E   F   G   H   I   J
first    8   7  38  48   4  30  27  31  45  51
second  46  58  78  51  10   1  55  85  79  73
third   84  78  77  70  96  86  10  88  70  95
fourth  46  65  33  60   9  99  99  47  68  27
fifth    7   7   7   7   7   7   7   7   7   7

In [60]:
org.loc[:,'J']

first     51
second    73
third     95
fourth    27
fifth      7
Name: J, dtype: int64

cannot find the solution to add by index the element of first row andc first column and substitute on first row on J and so on...