In [48]:
import pandas as pd
import numpy as np
from dateutil.parser import parse

In [49]:
a=np.arange(6,100,4)

In [50]:
a

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70,
       74, 78, 82, 86, 90, 94, 98])

In [51]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)

[ 1.  2.  3. nan  5.  6.  7. nan]


In [52]:
a=a[~np.isnan(a)]

In [53]:
a

array([1., 2., 3., 5., 6., 7.])

create a random numpy array that has a shape of (5, 6) filled with integers between 1 and 100. 
Then compute the maximum int for each row in the array

In [54]:
a=np.random.randint(1, 100, size=(5,6), dtype=int)

In [55]:
a

array([[85, 88, 22, 80, 75, 38],
       [66, 11, 70, 97, 25, 28],
       [ 7, 71, 15, 38, 92, 11],
       [14, 54, 57, 28, 54, 37],
       [ 3, 20, 79, 29, 16, 22]])

In [56]:
np.amax(a, axis=1)

array([88, 97, 92, 57, 79])

In [57]:
series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))

In [58]:
series

0      d
1      a
2      f
3      d
4      p
      ..
495    g
496    n
497    p
498    i
499    b
Length: 500, dtype: object

In [59]:
series.value_counts()

o    39
d    37
f    36
c    35
g    34
m    34
k    34
l    33
b    33
p    31
e    31
n    29
a    25
i    25
j    22
h    22
dtype: int64

In [60]:
sr=pd.DataFrame(series)

In [61]:
sr1=sr.apply(pd.value_counts).fillna(0)

In [62]:
sr1

0
o  39
d  37
f  36
c  35
g  34
m  34
k  34
l  33
b  33
p  31
e  31
n  29
a  25
i  25
j  22
h  22

In [64]:
date_series = pd.Series(['02 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])

In [65]:
date_series

0         02 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [66]:
date_series = date_series.map(lambda x:parse(x))

In [73]:
date_series.dt.day.tolist()

[2, 2, 7, 6, 12, 6]

In [74]:
date_series.dt.dayofyear.tolist()

[2, 276, 66, 126, 103, 96]

In [83]:
date_series.dt.isocalendar().week

0     1
1    39
2    10
3    19
4    15
5    14
Name: week, dtype: UInt32

In [89]:
date_series.dt.weekday.tolist()

[4, 6, 2, 1, 1, 5]